apiVersion: v1
kind: Service
metadata:
  name: {{ include "portainer.fullname" . }}
  labels:
    {{- include "portainer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.edgePort }}
      targetPort: edge
      protocol: TCP
      name: edge
  selector:
    {{- include "portainer.selectorLabels" . | nindent 4 }}
